### ISSUE TITLE
现在还没法用吗？ 我这边提示 Failed to resolve: me.ele.android:toyroom:0.1.1

### ISSUE THREAD

**Issue by liaofuyou** [eleme/ToyRoom#1]
compile 'xiaofei.library:shelly:0.2.6' 是可以下载下来的。但me.ele.android:toyroom:0.1.1就不行

**Comment by Xiaofei-it** [comment]
你好！你先用compile 'xiaofei.library:shelly:0.2.6'吧。目前两个库是一模一样的。

我查一下原因。

另外，我以后会在代码里加注释。目前注释不多，你可以参照各个文档里的用法写。

**Comment by liaofuyou** [comment]
抱歉，没有及时看到你的回复。我现在用的就是shelly:0.2.6，灰常感谢。

另外我想说的是，我是昨天晚上在稀土掘金上看到这个框架的，看的时候好鸡冻，都萌发了半夜起来回公司加班的念头。谢谢你带给我们这么好的项目。

**Comment by Xiaofei-it** [comment]
谢谢！我这个项目是去年一时兴起想起来的，一直到今年5月才开始写。

希望你看看源码，开发难度还是很大的。

目前也没打算大规模推广，因为我觉得这个库和其他库都不太一样，对很多人来说比较难理解。

**Comment by Xiaofei-it** [comment]
刚刚看了一下，可能bintray上包名冲突，我后面再查一下。

不过两个库其实是一样的，如果大家无法下载ToyRoom，那么直接下载Shelly就可以了。

**Comment by liaofuyou** [comment]
@Xiaofei-it  我也准备学习您的源码，感觉很酷，肯定能有很多收获！！！
